# Generated by Django 3.1.4 on 2021-01-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AditionalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'aditional_equipment',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fuel_type',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('power', models.FloatField()),
                ('consumation', models.FloatField()),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='wypozyczalnia.fueltype')),
            ],
            options={
                'db_table': 'engine',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('rok_produkcji', models.IntegerField()),
                ('cena_za_godzine', models.IntegerField()),
                ('dostepnosc', models.BooleanField(default=True)),
                ('klimatyzacja', models.BooleanField(default=True)),
                ('ilosc_drzwi', models.IntegerField()),
                ('ocena', models.FloatField(default=0)),
                ('photo', models.ImageField(default='no_image.png', upload_to='cars/%Y/%m/%d')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='wypozyczalnia.model')),
                ('opcjonalne_wyposazenie', models.ManyToManyField(related_name='cars', to='wypozyczalnia.AditionalEquipment')),
                ('silnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='wypozyczalnia.engine')),
            ],
            options={
                'db_table': 'car',
                'ordering': ('model',),
            },
        ),
    ]
