# Generated by Django 3.1.4 on 2021-04-20 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'db_table': 'segment',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='ocena',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.FloatField(default=0)),
                ('komentarz', models.TextField(blank=True)),
                ('auto_oceniane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.car')),
                ('osoba_oceniajaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ocena',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='wypozyczalnia.segment'),
        ),
    ]
