# Generated by Django 3.1.4 on 2021-01-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='no-image.png', upload_to='cars/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
