# Generated by Django 3.1.4 on 2021-01-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_auto_20210124_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='zdjecie',
            new_name='photo',
        ),
    ]
