# Generated by Django 3.1.4 on 2021-01-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_auto_20210115_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to='cars/%Y/%m/%d'),
        ),
    ]
