# Generated by Django 3.1.4 on 2021-01-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_auto_20210124_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo',
            new_name='zdjecie',
        ),
    ]
